language: go
go: 1.3

services:
  - mongodb # 2.4.12

install:
  - pwd
  - ls
  - export GOPATH=`pwd`
  - echo $GOPATH
  # - go install github.com/revel/cmd/revel
  - cd src/github.com/leanote/leanote
  - pwd
  - ls

script:
  - mongo --version
  - mongorestore -h localhost -d leanote --directoryperdb ./mongodb_backup/leanote_install_data/
  - go test github.com/leanote/leanote/app/tests
  - go build -ldflags -X github.com/leanote/leanote/app
  # - revel build github.com/leanote/leanote tmp
  # OK